---
- name: Manage OpenStack Servers
  hosts: control_node
  #gather_facts: false
  become: false
  collections:
    - gpte.openstack

  vars: 
    distribution: '{{ ansible_distribution | lower }}'
    distribution_version: '{{ ansible_distribution_version }}'

  tasks:
    - name: debug
      debug:
        msg:
          - "distr: {{ distribution }}"
          - "distri version: {{ distribution_version }}"

  #roles:

  #  - openstack_manage_servers

...
