---
- name: Manage OpenStack Servers
  hosts: control_node
  #gather_facts: false
  become: false
  collections:
    - gpte.openstack

  tasks:
    - name: debug
      debug:
        msg:
          - "distri : {{ ansible_facts['distribution'] | lower }}"
          - "distri2 : {{ ansible_facts['distribution']  }}"
          - "ditri ver: {{ ansible_facts['distribution_major_version'] }}"

    - name: debug
      debug:
        msg:
          - "all is find!"
      when: 
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"


  #roles:

  #  - openstack_manage_servers

...
