---
- hosts: control
  tasks:
    - debug:

- name: Servers configuration
  hosts: load_balancers,database_servers,app_servers
  gather_facts: true
  
  
  roles:

    - servers-configuration

- hosts: towers
  tasks:

    - name: Adding frontend into hosts
      lineinfile:
        state: present
        path: /etc/hosts
        line: "{{ hostvars[_fronthost].ansible_host }} frontend1"
      loop: "{{ groups['load_balancers'] }}"
      loop_control:
        loop_var: _fronthost
