---
# vars file for roles/apps-configuration
app_yum_packages:
  - autoconf
  - automake
  - git
  - gcc
  - libtool
  - python3
  - python3-psycopg2

pip_dependencies:
  - virtualenv
  - psycopg2-binary==2.8.6
